CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(1000)
);

CREATE TABLE rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INT,
    course_id BIGINT,
    FOREIGN KEY (course_id) REFERENCES course(id)
);

CREATE TABLE assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    course_id BIGINT,
    FOREIGN KEY (course_id) REFERENCES course(id)
);

CREATE TABLE author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE course_author (
    course_id BIGINT,
    author_id BIGINT,
    PRIMARY KEY (course_id, author_id),
    FOREIGN KEY (course_id) REFERENCES course(id),
    FOREIGN KEY (author_id) REFERENCES author(id)
);